services:
  stat_voice_bot:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AUDIO_FFMPEG_PATH=/usr/local/bin/ffmpeg
    restart: always
    volumes:
      - /dejavu:/usr/share/fonts/TTF/dejavu:ro
      - /ffmpeg:/usr/local/bin:ro
    tmpfs:
      - /tmp
      - /var/cache/fontconfig
    networks:
      app-network:

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400