spring:
  application:
    name: telegram_bot_for_processing_voice
telegram:
  bot:
    token:
    username: StatVoiceBot

connection:
  yandex:
    folder-id:
    token:
    url: https://stt.api.cloud.yandex.net
    default-language: ru-RU

yandex:
  token:
    url: http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token




