spring:
  application:
    name: telegram_bot_for_processing_voice
telegram:
  bot:
    token:
    username: StatVoiceBot

yandex:
  iam:
    url: https://iam.api.cloud.yandex.net/iam/v1/tokens
  stt:
    url: https://stt.api.cloud.yandex.net
  folder-id:
  default-language: ru-RU
  auth:
    id:
    service_account_id:
    private_key:


cache:
  yandexCloudToken: yandexCloudToken






